name: mpontom_suite_poc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Modules
  core:
    path: modules/core
  dependencies:
    path: modules/dependencies
  shared:
    path: modules/shared
  
  # Sub Apps
  margem:
    path: modules/apps/margem
  offerta:
    path: modules/apps/offerta

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
